/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_demo;


import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     
     */
    Connection con = null;
    Statement pst = null;
    
    public NewJFrame() {
        initComponents();
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(false);
        ViewDoctorsPanel.setVisible(false);
        UpdateDoctorPanel.setVisible(false);
        UpdatePatientPanel.setVisible(false);
        RegisterDoctorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        HMS_title = new javax.swing.JLabel();
        login_msg = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        userField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        MenuPanel = new javax.swing.JPanel();
        viewDoctorButton = new javax.swing.JButton();
        viewPateintsButton = new javax.swing.JButton();
        updateDoctorButton = new javax.swing.JButton();
        updatePatientButton = new javax.swing.JButton();
        RegisterDoctor = new javax.swing.JButton();
        AdmitPatientButton = new javax.swing.JButton();
        DischargePatientButton = new javax.swing.JButton();
        exitMenuButton = new javax.swing.JButton();
        menuTitle = new javax.swing.JLabel();
        ViewPatientsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ViewPatientBackButton = new javax.swing.JButton();
        ViewDoctorsPanel = new javax.swing.JPanel();
        ViewDoctorLabel = new javax.swing.JLabel();
        ViewDoctorBackButton = new javax.swing.JButton();
        UpdateDoctorPanel = new javax.swing.JPanel();
        searchDoctorLabel = new javax.swing.JLabel();
        doctorSearchField = new javax.swing.JTextField();
        SearchDoctorButton = new javax.swing.JButton();
        DoctorIdLabel = new javax.swing.JLabel();
        UpdateDoctorBackButton = new javax.swing.JButton();
        UpdatePatientPanel = new javax.swing.JPanel();
        UpdatePatientTitleLabel = new javax.swing.JLabel();
        PatientIdLabel = new javax.swing.JLabel();
        SearchPatientIDField = new javax.swing.JTextField();
        SearchPatientButton = new javax.swing.JButton();
        UpdatePatientBackButton = new javax.swing.JButton();
        RegisterDoctorPanel = new javax.swing.JPanel();
        RegDoctorTitleLabel = new javax.swing.JLabel();
        RegDoctorForm = new javax.swing.JLabel();
        DoctorNameLabel = new javax.swing.JLabel();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorIDLabel = new javax.swing.JLabel();
        DoctorSpecialistLabel = new javax.swing.JLabel();
        DoctorIDField = new javax.swing.JTextField();
        DoctorNameField = new javax.swing.JTextField();
        DoctorContactField = new javax.swing.JTextField();
        DoctSpecialFiled = new javax.swing.JTextField();
        DoctorSalaryLabel = new javax.swing.JLabel();
        DoctorSalaryField = new javax.swing.JTextField();
        RegisterDoctorButton = new javax.swing.JButton();
        RegDoctBackButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 400));

        HMS_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HMS_title.setText("HOSPITAL MANAGEMENT SYSTEM");

        login_msg.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        login_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_msg.setText("Please enter your username and password");
        login_msg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        userLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        passLabel.setText("Password");

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HMS_title, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PassField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(userField)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(HMS_title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        viewDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewDoctorButton.setText("View Doctors");
        viewDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorButtonActionPerformed(evt);
            }
        });

        viewPateintsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewPateintsButton.setText("View Patients");
        viewPateintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPateintsButtonActionPerformed(evt);
            }
        });

        updateDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateDoctorButton.setText("Update Doctor");
        updateDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorButtonActionPerformed(evt);
            }
        });

        updatePatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePatientButton.setText("Update Patient");
        updatePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientButtonActionPerformed(evt);
            }
        });

        RegisterDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegisterDoctor.setText("Register Doctor");
        RegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDoctorActionPerformed(evt);
            }
        });

        AdmitPatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdmitPatientButton.setText("Admit Pateint");

        DischargePatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DischargePatientButton.setText("Discharge Patient");

        exitMenuButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitMenuButton.setText("Exit");
        exitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuButtonActionPerformed(evt);
            }
        });

        menuTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("Main Menu");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DischargePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewPateintsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(AdmitPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(viewPateintsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(updateDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdmitPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DischargePatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patients");

        ViewPatientBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewPatientBackButton.setText("Back");
        ViewPatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPatientBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewPatientsPanelLayout = new javax.swing.GroupLayout(ViewPatientsPanel);
        ViewPatientsPanel.setLayout(ViewPatientsPanelLayout);
        ViewPatientsPanelLayout.setHorizontalGroup(
            ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                .addGroup(ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(ViewPatientBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        ViewPatientsPanelLayout.setVerticalGroup(
            ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(ViewPatientBackButton)
                .addGap(26, 26, 26))
        );

        ViewDoctorLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewDoctorLabel.setText("View Doctors");

        ViewDoctorBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewDoctorBackButton.setText("Back");
        ViewDoctorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDoctorBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewDoctorsPanelLayout = new javax.swing.GroupLayout(ViewDoctorsPanel);
        ViewDoctorsPanel.setLayout(ViewDoctorsPanelLayout);
        ViewDoctorsPanelLayout.setHorizontalGroup(
            ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                .addGroup(ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(ViewDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(ViewDoctorBackButton)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        ViewDoctorsPanelLayout.setVerticalGroup(
            ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addComponent(ViewDoctorBackButton)
                .addGap(25, 25, 25))
        );

        searchDoctorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchDoctorLabel.setText("Search the Doctor you want to update");

        doctorSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorSearchFieldActionPerformed(evt);
            }
        });

        SearchDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchDoctorButton.setText("Search");

        DoctorIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorIdLabel.setText("Doctor ID");

        UpdateDoctorBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateDoctorBackButton.setText("Back");
        UpdateDoctorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDoctorBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateDoctorPanelLayout = new javax.swing.GroupLayout(UpdateDoctorPanel);
        UpdateDoctorPanel.setLayout(UpdateDoctorPanelLayout);
        UpdateDoctorPanelLayout.setHorizontalGroup(
            UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addComponent(searchDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateDoctorBackButton)
                    .addComponent(doctorSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchDoctorButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDoctorPanelLayout.createSequentialGroup()
                    .addContainerGap(46, Short.MAX_VALUE)
                    .addComponent(DoctorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(238, Short.MAX_VALUE)))
        );
        UpdateDoctorPanelLayout.setVerticalGroup(
            UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchDoctorButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(UpdateDoctorBackButton)
                .addContainerGap())
            .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDoctorPanelLayout.createSequentialGroup()
                    .addContainerGap(69, Short.MAX_VALUE)
                    .addComponent(DoctorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(186, Short.MAX_VALUE)))
        );

        UpdatePatientTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdatePatientTitleLabel.setText("Search the Patient you want to update");

        PatientIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientIdLabel.setText("Patient ID");

        SearchPatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchPatientButton.setText("Search");
        SearchPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientButtonActionPerformed(evt);
            }
        });

        UpdatePatientBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdatePatientBackButton.setText("Back");
        UpdatePatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePatientBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdatePatientPanelLayout = new javax.swing.GroupLayout(UpdatePatientPanel);
        UpdatePatientPanel.setLayout(UpdatePatientPanelLayout);
        UpdatePatientPanelLayout.setHorizontalGroup(
            UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UpdatePatientTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                                .addComponent(PatientIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchPatientIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UpdatePatientBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        UpdatePatientPanelLayout.setVerticalGroup(
            UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(UpdatePatientTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchPatientIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchPatientButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(UpdatePatientBackButton)
                .addContainerGap())
        );

        RegDoctorTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegDoctorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegDoctorTitleLabel.setText("Register Doctor");

        RegDoctorForm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegDoctorForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegDoctorForm.setText("Please fill out the infotmation below");

        DoctorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorNameLabel.setText(" Name:");

        DoctorContactLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorContactLabel.setText("Contact");

        DoctorIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorIDLabel.setText("Doctor ID:");

        DoctorSpecialistLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorSpecialistLabel.setText("Specialization");

        DoctorSalaryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorSalaryLabel.setText("Salary");

        RegisterDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegisterDoctorButton.setText("Register");

        RegDoctBackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegDoctBackButton.setText("Back");
        RegDoctBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegDoctBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterDoctorPanelLayout = new javax.swing.GroupLayout(RegisterDoctorPanel);
        RegisterDoctorPanel.setLayout(RegisterDoctorPanelLayout);
        RegisterDoctorPanelLayout.setHorizontalGroup(
            RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(RegDoctorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(RegDoctorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(RegisterDoctorButton)
                            .addGap(18, 18, 18)
                            .addComponent(RegDoctBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterDoctorPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DoctorIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(DoctorNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DoctorContactLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                                    .addComponent(DoctorSpecialistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addComponent(DoctorSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DoctorIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctSpecialFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        RegisterDoctorPanelLayout.setVerticalGroup(
            RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegDoctorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegDoctorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DoctorIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DoctorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorContactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(DoctorContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addComponent(DoctSpecialFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(DoctorSpecialistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterDoctorButton)
                    .addComponent(RegDoctBackButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewPatientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewDoctorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UpdateDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UpdatePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegisterDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewPatientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ViewDoctorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UpdateDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UpdatePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(RegisterDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("myFrame");

        pack();
    }// </editor-fold>                        
    
    
    
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lab09?zeroDateTimeBehavior=CONVERT_TO_NULL", "root", "");
        //Statement pst =
        LoginPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }                                           

    private void viewDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(true);
    }                                                

    private void updateDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        UpdateDoctorPanel.setVisible(true);
        String id = doctorSearchField.getText();
    }                                                  

    private void doctorSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void updatePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        UpdatePatientPanel.setVisible(true);
    }                                                   

    private void ViewPatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        ViewPatientsPanel.setVisible(false);
        MenuPanel.setVisible(true);
        
    }                                                     

    private void ViewDoctorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        ViewDoctorsPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }                                                    

    private void UpdateDoctorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        // TODO add your handling code here:
        UpdateDoctorPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }                                                      

    private void UpdatePatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
        UpdatePatientPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }                                                       

    private void SearchPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void viewPateintsButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(true);
    }                                                  

    private void exitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good Bye...!");
        System.exit(0);
    }                                              

    private void RegDoctBackButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        RegisterDoctorPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }                                                 

    private void RegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        RegisterDoctorPanel.setVisible(true);
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AdmitPatientButton;
    private javax.swing.JButton DischargePatientButton;
    private javax.swing.JTextField DoctSpecialFiled;
    private javax.swing.JTextField DoctorContactField;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JTextField DoctorIDField;
    private javax.swing.JLabel DoctorIDLabel;
    private javax.swing.JLabel DoctorIdLabel;
    private javax.swing.JTextField DoctorNameField;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JTextField DoctorSalaryField;
    private javax.swing.JLabel DoctorSalaryLabel;
    private javax.swing.JLabel DoctorSpecialistLabel;
    private javax.swing.JLabel HMS_title;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel PatientIdLabel;
    private javax.swing.JButton RegDoctBackButton;
    private javax.swing.JLabel RegDoctorForm;
    private javax.swing.JLabel RegDoctorTitleLabel;
    private javax.swing.JButton RegisterDoctor;
    private javax.swing.JButton RegisterDoctorButton;
    private javax.swing.JPanel RegisterDoctorPanel;
    private javax.swing.JButton SearchDoctorButton;
    private javax.swing.JButton SearchPatientButton;
    private javax.swing.JTextField SearchPatientIDField;
    private javax.swing.JButton UpdateDoctorBackButton;
    private javax.swing.JPanel UpdateDoctorPanel;
    private javax.swing.JButton UpdatePatientBackButton;
    private javax.swing.JPanel UpdatePatientPanel;
    private javax.swing.JLabel UpdatePatientTitleLabel;
    private javax.swing.JButton ViewDoctorBackButton;
    private javax.swing.JLabel ViewDoctorLabel;
    private javax.swing.JPanel ViewDoctorsPanel;
    private javax.swing.JButton ViewPatientBackButton;
    private javax.swing.JPanel ViewPatientsPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField doctorSearchField;
    private javax.swing.JButton exitMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login_msg;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel searchDoctorLabel;
    private javax.swing.JButton updateDoctorButton;
    private javax.swing.JButton updatePatientButton;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton viewDoctorButton;
    private javax.swing.JButton viewPateintsButton;
    // End of variables declaration                   
}
