/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package db_demo;

//import com.sun.jdi.connect.spi.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getString;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DELL
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     
     */
    Connection con = null;
    Statement pst = null;
    
    public NewJFrame() {
        initComponents();
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(false);
        ViewDoctorsPanel.setVisible(false);
        UpdateDoctorPanel.setVisible(false);
        UpdatePatientPanel.setVisible(false);
        RegisterDoctorPanel.setVisible(false);
        AdmitPatientPanel.setVisible(false);
        DischargePatientPanel.setVisible(false);
        //jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        HMS_title = new javax.swing.JLabel();
        login_msg = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        userField = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        MenuPanel = new javax.swing.JPanel();
        viewDoctorButton = new javax.swing.JButton();
        viewPateintsButton = new javax.swing.JButton();
        updateDoctorButton = new javax.swing.JButton();
        updatePatientButton = new javax.swing.JButton();
        RegisterDoctor = new javax.swing.JButton();
        AdmitPatientButton = new javax.swing.JButton();
        DischargePatientButton = new javax.swing.JButton();
        exitMenuButton = new javax.swing.JButton();
        menuTitle = new javax.swing.JLabel();
        ViewPatientsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ViewPatientBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatient = new javax.swing.JTable();
        ViewDoctorsPanel = new javax.swing.JPanel();
        ViewDoctorLabel = new javax.swing.JLabel();
        ViewDoctorBackButton = new javax.swing.JButton();
        UpdateDoctorPanel = new javax.swing.JPanel();
        searchDoctorLabel = new javax.swing.JLabel();
        doctorSearchField = new javax.swing.JTextField();
        SearchDoctorButton = new javax.swing.JButton();
        DoctorIdLabel = new javax.swing.JLabel();
        UpdateDoctorBackButton = new javax.swing.JButton();
        DoctorDataLabel1 = new javax.swing.JLabel();
        DoctorDataLabel2 = new javax.swing.JLabel();
        UpdatePatientPanel = new javax.swing.JPanel();
        UpdatePatientTitleLabel = new javax.swing.JLabel();
        PatientIdLabel = new javax.swing.JLabel();
        SearchPatientIDField = new javax.swing.JTextField();
        SearchPatientButton = new javax.swing.JButton();
        UpdatePatientBackButton = new javax.swing.JButton();
        PatientDataLabel1 = new javax.swing.JLabel();
        PatientDataLabel2 = new javax.swing.JLabel();
        RegisterDoctorPanel = new javax.swing.JPanel();
        RegDoctorTitleLabel = new javax.swing.JLabel();
        RegDoctorForm = new javax.swing.JLabel();
        DoctorNameLabel = new javax.swing.JLabel();
        DoctorContactLabel = new javax.swing.JLabel();
        DoctorIDLabel = new javax.swing.JLabel();
        DoctorSpecialistLabel = new javax.swing.JLabel();
        DoctorIDField = new javax.swing.JTextField();
        DoctorNameField = new javax.swing.JTextField();
        DoctorContactField = new javax.swing.JTextField();
        DoctSpecialFiled = new javax.swing.JTextField();
        DoctorSalaryLabel = new javax.swing.JLabel();
        DoctorSalaryField = new javax.swing.JTextField();
        RegisterDoctorButton = new javax.swing.JButton();
        RegDoctBackButton = new javax.swing.JButton();
        AdmitPatientPanel = new javax.swing.JPanel();
        AdmitPatientLabel = new javax.swing.JLabel();
        PatientFormLabel = new javax.swing.JLabel();
        patientIDLabel = new javax.swing.JLabel();
        PatientIDField = new javax.swing.JTextField();
        PatientNameLabel = new javax.swing.JLabel();
        PatientNameField = new javax.swing.JTextField();
        PatientAgeLabel = new javax.swing.JLabel();
        PatientAgeField = new javax.swing.JTextField();
        PatientAddressLabel = new javax.swing.JLabel();
        PatientAddressField = new javax.swing.JTextField();
        PatientGenderLabel = new javax.swing.JLabel();
        PatientGenderField = new javax.swing.JTextField();
        PatientWardLabel = new javax.swing.JLabel();
        PatientWardField = new javax.swing.JTextField();
        AdmitPatientPanelButton = new javax.swing.JButton();
        AdmitPatientBack = new javax.swing.JButton();
        DischargePatientPanel = new javax.swing.JPanel();
        DischargePatientTitle = new javax.swing.JLabel();
        DischargePatientLabel = new javax.swing.JLabel();
        DischargePatientIDLabel = new javax.swing.JLabel();
        DischargePatientIDField = new javax.swing.JTextField();
        DischargeSearchButton = new javax.swing.JButton();
        DischargePatientBackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(420, 400));

        LoginPanel.setBackground(new java.awt.Color(204, 204, 204));
        LoginPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        HMS_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HMS_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HMS_title.setText("HOSPITAL MANAGEMENT SYSTEM");

        login_msg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        login_msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_msg.setText("Please enter your username and password");
        login_msg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        userLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        userLabel.setText("Username");

        passLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        passLabel.setText("Password");

        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                .addComponent(passLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PassField, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addComponent(userField)))
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                            .addGap(125, 125, 125)
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(HMS_title, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginPanelLayout.setVerticalGroup(
            LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(HMS_title, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(login_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(LoginButton)
                .addGap(47, 47, 47))
        );

        viewDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewDoctorButton.setText("View Doctors");
        viewDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDoctorButtonActionPerformed(evt);
            }
        });

        viewPateintsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        viewPateintsButton.setText("View Patients");
        viewPateintsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPateintsButtonActionPerformed(evt);
            }
        });

        updateDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateDoctorButton.setText("Update Doctor");
        updateDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDoctorButtonActionPerformed(evt);
            }
        });

        updatePatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePatientButton.setText("Update Patient");
        updatePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientButtonActionPerformed(evt);
            }
        });

        RegisterDoctor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegisterDoctor.setText("Register Doctor");
        RegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterDoctorActionPerformed(evt);
            }
        });

        AdmitPatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdmitPatientButton.setText("Admit Pateint");
        AdmitPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmitPatientButtonActionPerformed(evt);
            }
        });

        DischargePatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DischargePatientButton.setText("Discharge Patient");
        DischargePatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DischargePatientButtonActionPerformed(evt);
            }
        });

        exitMenuButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitMenuButton.setText("Exit");
        exitMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuButtonActionPerformed(evt);
            }
        });

        menuTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        menuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuTitle.setText("Main Menu");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DischargePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RegisterDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewPateintsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(AdmitPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(viewPateintsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatePatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(updateDoctorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdmitPatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DischargePatientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Patients");

        ViewPatientBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewPatientBackButton.setText("Back");
        ViewPatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPatientBackButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Age", "Address", "gender", "Ward"
            }
        ));
        jScrollPane1.setViewportView(tablePatient);

        javax.swing.GroupLayout ViewPatientsPanelLayout = new javax.swing.GroupLayout(ViewPatientsPanel);
        ViewPatientsPanel.setLayout(ViewPatientsPanelLayout);
        ViewPatientsPanelLayout.setHorizontalGroup(
            ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                .addGroup(ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(ViewPatientBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        ViewPatientsPanelLayout.setVerticalGroup(
            ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(ViewPatientBackButton)
                .addGap(26, 26, 26))
            .addGroup(ViewPatientsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ViewPatientsPanelLayout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );

        ViewDoctorLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ViewDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ViewDoctorLabel.setText("View Doctors");

        ViewDoctorBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ViewDoctorBackButton.setText("Back");
        ViewDoctorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDoctorBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ViewDoctorsPanelLayout = new javax.swing.GroupLayout(ViewDoctorsPanel);
        ViewDoctorsPanel.setLayout(ViewDoctorsPanelLayout);
        ViewDoctorsPanelLayout.setHorizontalGroup(
            ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                .addGroup(ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(ViewDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(ViewDoctorBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        ViewDoctorsPanelLayout.setVerticalGroup(
            ViewDoctorsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDoctorsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ViewDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(ViewDoctorBackButton)
                .addGap(26, 26, 26))
        );

        searchDoctorLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchDoctorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchDoctorLabel.setText("Search the Doctor you want to update");

        doctorSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorSearchFieldActionPerformed(evt);
            }
        });

        SearchDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchDoctorButton.setText("Search");
        SearchDoctorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDoctorButtonActionPerformed(evt);
            }
        });

        DoctorIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorIdLabel.setText("Doctor ID");

        UpdateDoctorBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdateDoctorBackButton.setText("Back");
        UpdateDoctorBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateDoctorBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateDoctorPanelLayout = new javax.swing.GroupLayout(UpdateDoctorPanel);
        UpdateDoctorPanel.setLayout(UpdateDoctorPanelLayout);
        UpdateDoctorPanelLayout.setHorizontalGroup(
            UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(DoctorDataLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(DoctorDataLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 37, Short.MAX_VALUE))
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateDoctorBackButton)
                    .addComponent(doctorSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchDoctorButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDoctorPanelLayout.createSequentialGroup()
                    .addContainerGap(53, Short.MAX_VALUE)
                    .addComponent(DoctorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(244, Short.MAX_VALUE)))
        );
        UpdateDoctorPanelLayout.setVerticalGroup(
            UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateDoctorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchDoctorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doctorSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchDoctorButton)
                .addGap(18, 18, 18)
                .addComponent(DoctorDataLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DoctorDataLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(UpdateDoctorBackButton)
                .addContainerGap())
            .addGroup(UpdateDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateDoctorPanelLayout.createSequentialGroup()
                    .addContainerGap(72, Short.MAX_VALUE)
                    .addComponent(DoctorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(256, Short.MAX_VALUE)))
        );

        UpdatePatientTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UpdatePatientTitleLabel.setText("Search the Patient you want to update");

        PatientIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientIdLabel.setText("Patient ID");

        SearchPatientButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchPatientButton.setText("Search");
        SearchPatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchPatientButtonActionPerformed(evt);
            }
        });

        UpdatePatientBackButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        UpdatePatientBackButton.setText("Back");
        UpdatePatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePatientBackButtonActionPerformed(evt);
            }
        });

        PatientDataLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        PatientDataLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout UpdatePatientPanelLayout = new javax.swing.GroupLayout(UpdatePatientPanel);
        UpdatePatientPanel.setLayout(UpdatePatientPanelLayout);
        UpdatePatientPanelLayout.setHorizontalGroup(
            UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UpdatePatientTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                                    .addComponent(PatientIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(SearchPatientIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                            .addGap(124, 124, 124)
                            .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(SearchPatientButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UpdatePatientBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(PatientDataLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientDataLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        UpdatePatientPanelLayout.setVerticalGroup(
            UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdatePatientPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(UpdatePatientTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdatePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchPatientIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchPatientButton)
                .addGap(27, 27, 27)
                .addComponent(PatientDataLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PatientDataLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(UpdatePatientBackButton)
                .addContainerGap())
        );

        RegDoctorTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegDoctorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegDoctorTitleLabel.setText("Register Doctor");

        RegDoctorForm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RegDoctorForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RegDoctorForm.setText("Please fill out the infotmation below");

        DoctorNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorNameLabel.setText(" Name:");

        DoctorContactLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorContactLabel.setText("Contact");

        DoctorIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorIDLabel.setText("Doctor ID:");

        DoctorSpecialistLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorSpecialistLabel.setText("Specialization");

        DoctorSalaryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DoctorSalaryLabel.setText("Salary");

        RegisterDoctorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegisterDoctorButton.setText("Register");

        RegDoctBackButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegDoctBackButton.setText("Back");
        RegDoctBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegDoctBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegisterDoctorPanelLayout = new javax.swing.GroupLayout(RegisterDoctorPanel);
        RegisterDoctorPanel.setLayout(RegisterDoctorPanelLayout);
        RegisterDoctorPanelLayout.setHorizontalGroup(
            RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(RegDoctorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                            .addGap(85, 85, 85)
                            .addComponent(RegisterDoctorButton)
                            .addGap(18, 18, 18)
                            .addComponent(RegDoctBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, RegisterDoctorPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(DoctorIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoctorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(DoctorContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(DoctorSpecialistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                                .addComponent(DoctorSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DoctorIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctSpecialFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DoctorSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(RegDoctorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        RegisterDoctorPanelLayout.setVerticalGroup(
            RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegDoctorTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegDoctorForm, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(RegisterDoctorPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(DoctorIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoctorNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(DoctorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoctorContactLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DoctorContactField, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DoctorSpecialistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctSpecialFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DoctorSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DoctorSalaryField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(RegisterDoctorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterDoctorButton)
                    .addComponent(RegDoctBackButton))
                .addContainerGap())
        );

        AdmitPatientLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        AdmitPatientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdmitPatientLabel.setText("Admit Patient");

        PatientFormLabel.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        PatientFormLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PatientFormLabel.setText("Please fill out patient's information below");

        patientIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        patientIDLabel.setText("ID");

        PatientNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PatientNameLabel.setText("Name");

        PatientAgeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        PatientAgeLabel.setText("Age");

        PatientAddressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientAddressLabel.setText("Address");

        PatientGenderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientGenderLabel.setText("Gender");

        PatientWardLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PatientWardLabel.setText("Ward Info");

        AdmitPatientPanelButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdmitPatientPanelButton.setText("Admit");

        AdmitPatientBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AdmitPatientBack.setText("Back");
        AdmitPatientBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmitPatientBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdmitPatientPanelLayout = new javax.swing.GroupLayout(AdmitPatientPanel);
        AdmitPatientPanel.setLayout(AdmitPatientPanelLayout);
        AdmitPatientPanelLayout.setHorizontalGroup(
            AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(AdmitPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(PatientGenderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PatientAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                                .addComponent(PatientAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PatientNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(patientIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(PatientWardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PatientAddressField)
                                    .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                                        .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PatientIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(PatientGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(PatientWardField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(PatientFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(AdmitPatientPanelButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdmitPatientBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AdmitPatientPanelLayout.setVerticalGroup(
            AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdmitPatientPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AdmitPatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientFormLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PatientAgeField)
                    .addComponent(PatientAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientAddressLabel)
                    .addComponent(PatientAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientGenderLabel)
                    .addComponent(PatientGenderField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PatientWardLabel)
                    .addComponent(PatientWardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AdmitPatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdmitPatientPanelButton)
                    .addComponent(AdmitPatientBack))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        DischargePatientTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DischargePatientTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DischargePatientTitle.setText("Discharge Patient");

        DischargePatientLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        DischargePatientLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DischargePatientLabel.setText("Search the patient you want to discharge");

        DischargePatientIDLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DischargePatientIDLabel.setText("ID");

        DischargeSearchButton.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DischargeSearchButton.setText("Search");

        DischargePatientBackButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DischargePatientBackButton.setText("Back");
        DischargePatientBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DischargePatientBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DischargePatientPanelLayout = new javax.swing.GroupLayout(DischargePatientPanel);
        DischargePatientPanel.setLayout(DischargePatientPanelLayout);
        DischargePatientPanelLayout.setHorizontalGroup(
            DischargePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DischargePatientPanelLayout.createSequentialGroup()
                .addGroup(DischargePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DischargePatientPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(DischargePatientTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DischargePatientPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(DischargePatientIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(DischargePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DischargePatientBackButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(DischargePatientIDField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DischargeSearchButton)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DischargePatientPanelLayout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(DischargePatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        DischargePatientPanelLayout.setVerticalGroup(
            DischargePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DischargePatientPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(DischargePatientTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DischargePatientLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DischargePatientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DischargePatientIDLabel)
                    .addComponent(DischargePatientIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DischargeSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(DischargePatientBackButton)
                .addContainerGap())
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 32, Short.MAX_VALUE)
                    .addComponent(ViewPatientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ViewDoctorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 59, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 31, Short.MAX_VALUE)
                    .addComponent(UpdateDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 32, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(UpdatePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(RegisterDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 28, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 33, Short.MAX_VALUE)
                    .addComponent(AdmitPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 34, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 28, Short.MAX_VALUE)
                    .addComponent(DischargePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 41, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 30, Short.MAX_VALUE)
                    .addComponent(ViewPatientsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 30, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(ViewDoctorsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 58, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(UpdateDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 26, Short.MAX_VALUE)
                    .addComponent(UpdatePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(RegisterDoctorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 27, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 25, Short.MAX_VALUE)
                    .addComponent(AdmitPatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 26, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 29, Short.MAX_VALUE)
                    .addComponent(DischargePatientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 29, Short.MAX_VALUE)))
        );

        LoginPanel.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("myFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        try {
            // TODO add your handling code here:
            String sql = "Select * FROM user";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            boolean flag = false;
            if(rs.next())
            {
                String name = rs.getString(1);
                String password = rs.getString(2);
                String pwd = new String(PassField.getPassword());
                if(name.equals(userField.getText()) && password.equals(pwd))
                {    
                    JOptionPane.showMessageDialog(null, "Login Successful..");
                    flag = true;
                    LoginPanel.setVisible(false);
                    MenuPanel.setVisible(true);  
                }
            }
            if(flag == false)
            {
                JOptionPane.showMessageDialog(null, "Username and password NOT matched");
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Database Error");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void viewDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDoctorButtonActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(true);
    }//GEN-LAST:event_viewDoctorButtonActionPerformed

    private void updateDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDoctorButtonActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        UpdateDoctorPanel.setVisible(true);
        String id = doctorSearchField.getText();
    }//GEN-LAST:event_updateDoctorButtonActionPerformed

    private void doctorSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorSearchFieldActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_doctorSearchFieldActionPerformed

    private void updatePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientButtonActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        UpdatePatientPanel.setVisible(true);
    }//GEN-LAST:event_updatePatientButtonActionPerformed

    private void ViewPatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPatientBackButtonActionPerformed
        // TODO add your handling code here:
        ViewPatientsPanel.setVisible(false);
        MenuPanel.setVisible(true);
        
    }//GEN-LAST:event_ViewPatientBackButtonActionPerformed

    private void ViewDoctorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDoctorBackButtonActionPerformed
        // TODO add your handling code here:
        ViewDoctorsPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_ViewDoctorBackButtonActionPerformed

    private void UpdateDoctorBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateDoctorBackButtonActionPerformed
        // TODO add your handling code here:
        UpdateDoctorPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_UpdateDoctorBackButtonActionPerformed

    private void UpdatePatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePatientBackButtonActionPerformed
        // TODO add your handling code here:
        UpdatePatientPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_UpdatePatientBackButtonActionPerformed

    private void SearchPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchPatientButtonActionPerformed
        // TODO add your handling code here:
         String query = "SELECT * FROM patients";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.createStatement();
            ResultSet rs = pst.executeQuery(query);
            boolean flag = false;
            if(rs.next())
            {
                String id = rs.getString(1);
                System.out.println(id);
                if(id.equals(SearchPatientIDField.getText()))
                {   
                    //SearchPatientButton.setVisible(false);
                    PatientDataLabel1.setText("ID: "+ rs.getString(1)+",  Name: "+ rs.getString(2)+ ",  Age: "+rs.getString(3)+ ",  Address: " +rs.getString(4)+ ",");
                    PatientDataLabel2.setText("Gender: "+rs.getString(5)+ ",  Ward info: " +rs.getString(6));
                }
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
    }//GEN-LAST:event_SearchPatientButtonActionPerformed

    private void viewPateintsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPateintsButtonActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        ViewPatientsPanel.setVisible(true);
        String sql = "Select * FROM patients";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            while(rs.next())
            {
                String id = String.valueOf(rs.getInt("P_id"));
                String name = rs.getString("P_name");
                String age = String.valueOf(rs.getInt("Age"));
                String address = rs.getString("Address");
                String gender = rs.getString("Gender");
                String ward = String.valueOf(rs.getInt("WardNumber"));
                String data[] = {id, name, age, address, gender, ward};
                DefaultTableModel tm = (DefaultTableModel)tablePatient.getModel();
                tm.addRow(data);
            }
            con.close();
        }
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_viewPateintsButtonActionPerformed

    private void exitMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Good Bye...!");
        System.exit(0);
    }//GEN-LAST:event_exitMenuButtonActionPerformed

    private void RegDoctBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegDoctBackButtonActionPerformed
        // TODO add your handling code here:
        RegisterDoctorPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_RegDoctBackButtonActionPerformed

    private void RegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterDoctorActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        RegisterDoctorPanel.setVisible(true);
    }//GEN-LAST:event_RegisterDoctorActionPerformed

    private void AdmitPatientBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmitPatientBackActionPerformed
        // TODO add your handling code here:
        AdmitPatientPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_AdmitPatientBackActionPerformed

    private void AdmitPatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmitPatientButtonActionPerformed
        // TODO add your handling code here
        MenuPanel.setVisible(false);
        AdmitPatientPanel.setVisible(true);
    }//GEN-LAST:event_AdmitPatientButtonActionPerformed

    private void DischargePatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DischargePatientButtonActionPerformed
        // TODO add your handling code here:
        MenuPanel.setVisible(false);
        DischargePatientPanel.setVisible(true);
    }//GEN-LAST:event_DischargePatientButtonActionPerformed

    private void DischargePatientBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DischargePatientBackButtonActionPerformed
        // TODO add your handling code here:
        DischargePatientPanel.setVisible(false);
        MenuPanel.setVisible(true);
    }//GEN-LAST:event_DischargePatientBackButtonActionPerformed

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassFieldActionPerformed

    private void SearchDoctorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDoctorButtonActionPerformed
        // TODO add your handling code here:
        String sql = "Select * FROM doctors";
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hms?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst = con.createStatement();
            ResultSet rs = pst.executeQuery(sql);
            boolean flag = false;
            if(rs.next())
            {
                String id = rs.getString(1);
                System.out.println(id);
                if(id == (doctorSearchField.getText()))
                {    
                    DoctorDataLabel1.setText("ID: "+ rs.getString(1)+ ",  Name: "+ rs.getString(2) + ",  " + rs.getString(3) +",");
                    DoctorDataLabel1.setText(": " + rs.getString(5));
                }
            }
        } 
        catch (SQLException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_SearchDoctorButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdmitPatientBack;
    private javax.swing.JButton AdmitPatientButton;
    private javax.swing.JLabel AdmitPatientLabel;
    private javax.swing.JPanel AdmitPatientPanel;
    private javax.swing.JButton AdmitPatientPanelButton;
    private javax.swing.JButton DischargePatientBackButton;
    private javax.swing.JButton DischargePatientButton;
    private javax.swing.JTextField DischargePatientIDField;
    private javax.swing.JLabel DischargePatientIDLabel;
    private javax.swing.JLabel DischargePatientLabel;
    private javax.swing.JPanel DischargePatientPanel;
    private javax.swing.JLabel DischargePatientTitle;
    private javax.swing.JButton DischargeSearchButton;
    private javax.swing.JTextField DoctSpecialFiled;
    private javax.swing.JTextField DoctorContactField;
    private javax.swing.JLabel DoctorContactLabel;
    private javax.swing.JLabel DoctorDataLabel1;
    private javax.swing.JLabel DoctorDataLabel2;
    private javax.swing.JTextField DoctorIDField;
    private javax.swing.JLabel DoctorIDLabel;
    private javax.swing.JLabel DoctorIdLabel;
    private javax.swing.JTextField DoctorNameField;
    private javax.swing.JLabel DoctorNameLabel;
    private javax.swing.JTextField DoctorSalaryField;
    private javax.swing.JLabel DoctorSalaryLabel;
    private javax.swing.JLabel DoctorSpecialistLabel;
    private javax.swing.JLabel HMS_title;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JTextField PatientAddressField;
    private javax.swing.JLabel PatientAddressLabel;
    private javax.swing.JTextField PatientAgeField;
    private javax.swing.JLabel PatientAgeLabel;
    private javax.swing.JLabel PatientDataLabel1;
    private javax.swing.JLabel PatientDataLabel2;
    private javax.swing.JLabel PatientFormLabel;
    private javax.swing.JTextField PatientGenderField;
    private javax.swing.JLabel PatientGenderLabel;
    private javax.swing.JTextField PatientIDField;
    private javax.swing.JLabel PatientIdLabel;
    private javax.swing.JTextField PatientNameField;
    private javax.swing.JLabel PatientNameLabel;
    private javax.swing.JTextField PatientWardField;
    private javax.swing.JLabel PatientWardLabel;
    private javax.swing.JButton RegDoctBackButton;
    private javax.swing.JLabel RegDoctorForm;
    private javax.swing.JLabel RegDoctorTitleLabel;
    private javax.swing.JButton RegisterDoctor;
    private javax.swing.JButton RegisterDoctorButton;
    private javax.swing.JPanel RegisterDoctorPanel;
    private javax.swing.JButton SearchDoctorButton;
    private javax.swing.JButton SearchPatientButton;
    private javax.swing.JTextField SearchPatientIDField;
    private javax.swing.JButton UpdateDoctorBackButton;
    private javax.swing.JPanel UpdateDoctorPanel;
    private javax.swing.JButton UpdatePatientBackButton;
    private javax.swing.JPanel UpdatePatientPanel;
    private javax.swing.JLabel UpdatePatientTitleLabel;
    private javax.swing.JButton ViewDoctorBackButton;
    private javax.swing.JLabel ViewDoctorLabel;
    private javax.swing.JPanel ViewDoctorsPanel;
    private javax.swing.JButton ViewPatientBackButton;
    private javax.swing.JPanel ViewPatientsPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField doctorSearchField;
    private javax.swing.JButton exitMenuButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel login_msg;
    private javax.swing.JLabel menuTitle;
    private javax.swing.JLabel passLabel;
    private javax.swing.JLabel patientIDLabel;
    private javax.swing.JLabel searchDoctorLabel;
    private javax.swing.JTable tablePatient;
    private javax.swing.JButton updateDoctorButton;
    private javax.swing.JButton updatePatientButton;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    private javax.swing.JButton viewDoctorButton;
    private javax.swing.JButton viewPateintsButton;
    // End of variables declaration//GEN-END:variables
}
